### ISSUE TITLE
[Question] Replace PSU fan

### ISSUE THREAD

**Issue by k-matti** [damianmoore/hp-server-fan-controller#1]
Hello, I have a question about replacing psu fun.
I bought Sunon HA40201V4-0000-999 but original screws does not fit the holes in Sunon are too big. 
How you mounted it properly?

**Comment by damianmoore** [comment]
Hmm, this was a while ago but I think the screws fitted OK for me. If you measure the holes to the nearest mm then you should be able to find matching bolts on eBay. If you get bolts that are a bit longer then you could screw nuts on the end also so you don't have to rely on the self-tapping.

**Comment by k-matti** [comment]
Thanks :)
